---
stages:
- build
- push

default:
  tags:
  - kubernetes
  - linux
  before_script:
  - mkdir -p .ssh && cp $SSH_KEY_ID_ED25519 .ssh/id_ed25519 && cp $SSH_KEY_ID_ED25519_PUB .ssh/id_ed25519.pub
  - ssh-keyscan gitlab.infra.mylectra.com >> .ssh/known_hosts
  - chown -R 1979:1979 . && chmod 0600 .ssh/*
  - while ! docker info >/dev/null 2>&1; do echo "Waiting for docker to start ..."; sleep 1; done
  - git fetch -q --unshallow origin +refs/tags/*:refs/tags/*
  - git fetch -q origin master:master
  - docker login lectrarepoeuwinfra.azurecr.io --username "$DOCKER_LECTRAREPOEUWINFRA_LOGIN" --password "$DOCKER_LECTRAREPOEUWINFRA_PASSWORD"
  - (cd /tmp/ && wget --no-verbose https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz)
  - export PATH=/usr/local/go/bin:$PATH

services:
- docker:19.03.13-dind
image:
  name: lectrarepoeuwinfra.azurecr.io/ubuntu-dind:v19.03.11_20201201

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  GO_VERSION: 1.15.6
  KUBERNETES_CPU_REQUEST: 500m
  KUBERNETES_CPU_LIMIT: 500m
  KUBERNETES_SERVICE_CPU_REQUEST: 2
  KUBERNETES_SERVICE_CPU_LIMIT: 2
  KUBERNETES_SERVICE_MEMORY_REQUEST: 4Gi
  KUBERNETES_SERVICE_MEMORY_LIMIT: 4Gi

docker-build:
  stage: build
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
  - apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
  - make build-image TRAEFIK_DEV_IMAGE=lectrarepoeuwinfra.azurecr.io/traefik-dev:$(git describe --tags | tr '+' '_') TRAEFIK_IMAGE=lectrarepoeuwinfra.azurecr.io/traefik:$(git describe --tags | tr '+' '_') VERSION=$(git describe --tags) VERSION_GIT=$(git describe --tags)

docker-push:
  stage: push
  rules:
  - if: '$CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
    when: manual
    allow_failure: true
  script:
  - apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
  - make build-image TRAEFIK_DEV_IMAGE=lectrarepoeuwinfra.azurecr.io/traefik-dev:$(git describe --tags | tr '+' '_') TRAEFIK_IMAGE=lectrarepoeuwinfra.azurecr.io/traefik:$(git describe --tags | tr '+' '_') VERSION=$(git describe --tags) VERSION_GIT=$(git describe --tags)
  - docker push lectrarepoeuwinfra.azurecr.io/traefik:$(git describe --tags | tr '+' '_')
